### ISSUE TITLE
chat room not working

### ISSUE THREAD

**Issue by meghakundu** [harri4007/social-network-demo#1]
The chat room does not show member list, room name etc.
![image](https://github.com/user-attachments/assets/4a63d0af-d100-4c83-b6f1-e2b07e1a3ab9)
Please help with this through the procedure for chatroom. @designatedcoder

**Comment by designatedcoder** [comment]
Can you see members in the Vue dev tools?

**Comment by meghakundu** [comment]
> Can you see members in the Vue dev tools?

No. After adding vuejs dev tools extension to chrome, vuejs not detected shows!
![image](https://github.com/user-attachments/assets/92365aff-1b43-420e-ba46-f7b93211fb7b)

**Comment by designatedcoder** [comment]
Hey I'm not really sure how to help without more info.  I'm not sure why the Vue dev tools aren't detecting the pages.  Are you running Vite or Mix?

**Comment by meghakundu** [comment]
> Hey I'm not really sure how to help without more info. I'm not sure why the Vue dev tools aren't detecting the pages. Are you running Vite or Mix?

![image](https://github.com/user-attachments/assets/459e6613-564f-48c5-a179-dc9a1dcfc69b)
after running vite, it shows the above. @meghakundu

**Comment by designatedcoder** [comment]
Okay, it looks like what's happened is you've downloaded the project without upgrading some the necessary packages.  This was built over 3 years ago with Laravel 8 and Inertia and this was using Vue 2 as well as Laravel Mix.  With outdated packages and no code changes, things won't work.  I can't tell if you've seeded the database using my factories/seeders. Before even doing that, you should upgrade everything to the current standard and decide if you want to use Mix or Vite as well as making the necessary changes for either.  I have some videos on my channel that serve as guides for migrating from one to the other that may help. I also have guides on how to upgrade Laravel projects scattered throughout my channel but there's loads of info both in the Laravel docs as well as the web to fill in any blanks I may have missed.  Hope this helps and good luck to you!

**Comment by meghakundu** [comment]
Thanks for the tip!
